### PR TITLE
car skin need to be unlock by having a higher maximum score

### PR DESCRIPTION
**Pull request by MaxHenn**
-skins need to have a highScore high enough
-add a small panel showing the score to have (and the highScore)

Signed-off-by: Maxence <maxence.hennekein@orange.fr>

### CODE REVIEW

**Comment by MaxHenn** [comment]
ah
ca rajoute les commits tout seul

**Comment by MaxHenn** [comment]
ah, je peux aussi re-ouvrir le pull
on en apprend tous les jours

**Review by AldricVS — APPROVED** [review]
I am not sure if the SheredPreferences in the CarChooserActivity is really a good choice. Also, it will be more relevent to add "private" keyword before all attributes in this activity (lines 27-30).

However, this is okay for me.

**Comment by MaxHenn** [comment]
> I am not sure if the SheredPreferences in the CarChooserActivity is really a good choice. Also, it will be more relevent to add "private" keyword before all attributes in this activity (lines 27-30).
> 
> However, this is okay for me.

as for the sharedPrefs, it is useful as a quick key/value save, for the selected car and for the highScore, so it is ok to use them
i will correct the missed private keywords, then merge

**Pull request merged**
